;;; claudemacs-repl-constants.el --- Precompiled constants for claudemacs-repl -*- lexical-binding: t -*-

;; This file is automatically generated by scripts/generate-constants.el
;; DO NOT EDIT MANUALLY

;;; Commentary:

;; Precompiled constants for cheatsheet functionality to improve performance
;; by avoiding runtime file I/O and parsing.

;;; Code:

(defconst claudemacs-repl-cheatsheet-candidates
  '(("claudemacs-repl-send-region" . "Send the text in region from START to END to claudemacs.  Category: Text Sender")
    ("claudemacs-repl-send-buffer" . "Send the entire current buffer to claudemacs.  Category: Text Sender")
    ("claudemacs-repl-send-rest-of-buffer" . "Send rest of buffer from cursor position to end to claudemacs.  Category: Text Sender")
    ("claudemacs-repl-send-line" . "Send the current line to claudemacs.  Category: Text Sender")
    ("claudemacs-repl-send-enter" . "Send enter key to claudemacs buffer.  Category: Text Sender")
    ("claudemacs-repl-send-1" . "Send \\\\='1\\\\=' to claudemacs buffer for numbered choice prompt.  Category: Text Sender")
    ("claudemacs-repl-send-2" . "Send \\\\='2\\\\=' to claudemacs buffer for numbered choice prompt.  Category: Text Sender")
    ("claudemacs-repl-send-3" . "Send \\\\='3\\\\=' to claudemacs buffer for numbered choice prompt.  Category: Text Sender")
    ("claudemacs-repl-send-escape" . "Send ESC key to claudemacs buffer.  Category: Text Sender")
    ("claudemacs-repl-open-project-input-file" . "Open or create project input file for DIRECTORY. If DIRECTORY is nil, use current `default-directory'. If project input file exists, open it directly. If not exists, create from template then open.  Category: Utilities")
    ("claudemacs-repl-start-claudemacs" . "Start claudemacs and change to appropriate directory. Determines directory from current buffer filename if it's a persistent file. Checks for existing sessions to prevent double startup.  Category: Session Controller")
    ("claudemacs-repl-finish-claudemacs" . "Terminate claudemacs session and close its buffer. Determines directory from current buffer filename if it's a persistent file. Calls claudemacs-kill for proper session termination.  Category: Session Controller")
    ("claudemacs-repl-setup-window-layout" . "Set up window layout with org file on left and claudemacs on right. This is the author's preference - customize as needed.  Category: Session Controller")
    ("claudemacs-repl-output-template" . "Output current template content to a new buffer for customization.  Category: Utilities")
    ("claudemacs-repl-status" . "Show detailed diagnostic information for troubleshooting connection issues.  Category: Utilities")
    ("claudemacs-repl-toggle-debug-mode" . "Toggle debug mode for claudemacs-repl operations.  Category: Utilities")
    ("claudemacs-repl-enable-debug-mode" . "Enable debug mode for claudemacs-repl operations.  Category: Utilities")
    ("claudemacs-repl-disable-debug-mode" . "Disable debug mode for claudemacs-repl operations.  Category: Utilities")
    ("claudemacs-repl-cheatsheet" . "Display interactive cheatsheet for claudemacs-repl commands.  Category: Command Palette"))
  "Precompiled list of cheatsheet candidates.
Each element is a cons cell (FUNCTION-NAME . DESCRIPTION).")

(defconst claudemacs-repl-cheatsheet-function-count
  19
  "Number of functions in cheatsheet.")

(provide 'claudemacs-repl-constants)

;;; claudemacs-repl-constants.el ends here
