;;; enkan-repl-constants.el --- Precompiled constants for enkan-repl -*- lexical-binding: t -*-

;; This file is automatically generated by scripts/generate-constants.el
;; DO NOT EDIT MANUALLY

;;; Commentary:

;; Precompiled constants for cheat-sheet functionality to improve performance
;; by avoiding runtime file I/O and parsing.

;;; Code:

(defconst enkan-repl-cheat-sheet-candidates
  '(("enkan-repl-send-region" . "Send the text in region from START to END to eat session.  Category: Text Sender")
     ("enkan-repl-send-buffer" . "Send the entire current buffer to eat session.  Category: Text Sender")
     ("enkan-repl-send-rest-of-buffer" . "Send rest of buffer from cursor position to end to eat session.  Category: Text Sender")
     ("enkan-repl-send-line" . "Send the current line to eat session.  Category: Text Sender")
     ("enkan-repl-send-enter" . "Send enter key to eat session buffer.  Category: Text Sender")
     ("enkan-repl-send-1" . "Send \\\\='1\\\\=' to eat session buffer for numbered choice prompt.  Category: Text Sender")
     ("enkan-repl-send-2" . "Send \\\\='2\\\\=' to eat session buffer for numbered choice prompt.  Category: Text Sender")
     ("enkan-repl-send-3" . "Send \\\\='3\\\\=' to eat session buffer for numbered choice prompt.  Category: Text Sender")
     ("enkan-repl-send-escape" . "Send ESC key to eat session buffer.  Category: Text Sender")
     ("enkan-repl-recenter-bottom" . "Move cursor to bottom of eat buffer for current directory.  Category: Utilities")
     ("enkan-repl-open-project-input-file" . "Open or create project input file for DIRECTORY. If DIRECTORY is nil, use current `default-directory'. If project input file exists, open it directly. If not exists, create from template then open.  Category: Utilities")
     ("enkan-repl-start-eat" . "Start eat terminal emulator session. Determines directory from current buffer filename if it's a persistent file. Checks for existing sessions to prevent double startup.  Category: Session Controller")
     ("enkan-repl-finish-eat" . "Terminate eat session and close its buffer. Determines directory from current buffer filename if it's a persistent file.  Category: Session Controller")
     ("enkan-repl-setup" . "Set up window layout with org file on left and eat on right. This is the author's preference - customize as needed.  Category: Session Controller")
     ("enkan-repl-status" . "Show detailed diagnostic information for troubleshooting connection issues.  Category: Utilities")
     ("enkan-repl-list-sessions" . "Display a list of active enkan sessions with interactive selection. Users can select a session, then choose action: (s)witch, (d)elete, or (q)uit.  Category: Session Controller")
     ("enkan-repl-cheat-sheet" . "Display interactive cheat-sheet for enkan-repl commands.  Category: Command Palette"))
  "Precompiled list of cheat-sheet candidates.
Each element is a cons cell (FUNCTION-NAME . DESCRIPTION).")

(defconst enkan-repl-cheat-sheet-function-count
  18
  "Number of functions in cheat-sheet.")

(provide 'enkan-repl-constants)

;;; enkan-repl-constants.el ends here
