name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Emacs 30.1
        uses: purcell/setup-emacs@master
        with:
          version: '30.1'
      
      - name: Run tests
        run: make test
      
      - name: Byte compile
        run: make compile